objdumpallocs: fix some off-by-one-instruction problems (affecting sphinx3) by using source coords from the allocation call site, not return site; while we're at it, make things more robust by using addr2line for source coords.

diff --git a/tools/objdumpallocs b/tools/objdumpallocs
--- a/tools/objdumpallocs
+++ b/tools/objdumpallocs
@@ -185,10 +185,41 @@ cat "$allocsites_tmpfile" 1>&2
 
 bytes_consumed=0
 
-while read address sym offset; do
+get_raw_addresses () {
+    while read address sym offset; do
+        # 0. skip blank lines
+        if [[ -z "${address}${sym}${offset}" ]]; then
+            continue
+        fi
+
+        echo 0x${address}
+    done <"$allocsites_tmpfile"
+}
+
+raw_addresses="$( get_raw_addresses )"
+
+addr2line_output="$( addr2line -a -e "$1" $raw_addresses | sed -r 's/^0x[0-9a-f]{8,}/\f&\t/' | tr -d '\n' | tr '\f' '\n' | tail -n+2 )"
+echo "addr2line said $addr2line_output" 1>&2
+
+addr2line_tmpfile="$(mktemp)"
+echo "addr2line temp file is $addr2line_tmpfile" 1>&2
+echo "$addr2line_output" > "$addr2line_tmpfile"
+
+# the way this should work: one loop generates return addresses and code context.
+# another loop does addr2line.
+# we merge the 
+
+generate_output_lines () {
+    while read address sym offset; do
     # 0. skip blank lines
     if [[ -z "${address}${sym}${offset}" ]]; then
         continue
+    fi
+    
+    read addr2line_addr addr2line_line <&3 || (echo "could not read addr2line file" 1>&2; false) || exit 1
+    
+    if [[ "$addr2line_addr" != 0x"$address" ]]; then
+        echo "Warning: $addr2line_addr != 0x$address" 1>&2
     fi
 
     # Now use the power of objdump -S to get the source line for that alloc.
@@ -207,7 +238,7 @@ while read address sym offset; do
     #echo "context the slow way: $context" 1>&2
     # instead of this, use sed
     next_chunk="$( tail -c+$(( $bytes_consumed + 1 )) "$tmpfile" 2>/dev/null | sed -r "/$regexp/ q" )"
-    #echo "fast way, next chunk: $next_chunk" 1>&2
+    # echo "fast way, next chunk: $next_chunk" 1>&2
     bytes_consumed=$(( $bytes_consumed + $( echo "$next_chunk" | wc -c ) ))
     #echo "bytes_consumed is now $bytes_consumed" 1>&2
     context="$( echo "$next_chunk" | tail -n31 )"
@@ -223,35 +254,35 @@ while read address sym offset; do
     if [[ -z "$file_line_header" ]]; then 
         echo "Warning: could not find source line for ${sym}${offset}, skipping" 1>&2
         echo "Context attempt was:"$'\n'"$with_file_line_header" 1>&2
-        continue
+    else
+        filename="$( readlink -f "$( echo "$file_line_header" | sed -r 's/:[0-9]+( \(discriminator [0-9]*\))?$//' )" )"
+        line_number="$( echo "$file_line_header" | sed -r 's/.*:([0-9]+)( \(discriminator [0-9]*\))?$/\1/' )"
+        # How many source lines are in the chunk?
+        # We grep -v out the header and anything that looks like an instruction disassembly line
+        source_lines="$( echo "$with_file_line_header" | egrep -v '^/.*:[0-9]+( \(discriminator [0-9]*\))?$' | egrep -v \
+            '^[0-9a-f]+[[:blank:]]*<.+(\+0x[0-9a-f]+)?>.*' )"
+        source_lines_count="$( echo "$source_lines" | wc -l )"
+        # HACK: if we didn't get anything, make sure we output a 1-line interval anyway
+        if [[ $source_lines_count -eq 0 ]]; then
+            echo "Warning: context for ${sym}${offset} appears to contain zero source lines. Context follows." 1>&2
+            echo "$source_lines" 1>&2
+            source_lines_count=1
+        fi
+        context_min="$( echo "$with_file_line_header" | tail -n+2 )"
+        #echo "context_min: $context_min" 1>&2
+        # 3. Filter out non-source lines., and collapse to a single line
+        source="$( echo "$context_min" | egrep -v "$line_regexp" | tr '\n' ' ' )" #"
+        #echo "source: $source" 1>&2
+        # 3a. collapse to a single line
+        source_oneline="$( echo "$source" | tr '\n' ' ' )"
+        #echo "source_oneline: $source_oneline" 1>&2
+        # 4. Get the first ident following the last occurrence of "new" or "sizeof"
+        token="$( echo "$source_oneline" | \
+        egrep '(new|sizeof)([^0-9a-z_]|$)' | \
+        sed -r 's/.*(new|sizeof)([^0-9a-zA-Z_]|$)/\2/' | \
+        sed -r 's/[^0-9a-zA-Z_]*([a-zA-Z0-9_ \*]+).*/\1/' | tr -s '[:blank:]' ' ' )" #"
+        #echo "token: $token" 1>&2
     fi
-    filename="$( readlink -f "$( echo "$file_line_header" | sed -r 's/:[0-9]+( \(discriminator [0-9]*\))?$//' )" )"
-    line_number="$( echo "$file_line_header" | sed -r 's/.*:([0-9]+)( \(discriminator [0-9]*\))?$/\1/' )"
-    # How many source lines are in the chunk?
-    # We grep -v out the header and anything that looks like an instruction disassembly line
-    source_lines="$( echo "$with_file_line_header" | egrep -v '^/.*:[0-9]+( \(discriminator [0-9]*\))?$' | egrep -v \
-        '^[0-9a-f]+[[:blank:]]*<.+(\+0x[0-9a-f]+)?>.*' )"
-    source_lines_count="$( echo "$source_lines" | wc -l )"
-    # HACK: if we didn't get anything, make sure we output a 1-line interval anyway
-    if [[ $source_lines_count -eq 0 ]]; then
-        echo "Warning: context for ${sym}${offset} appears to contain zero source lines. Context follows." 1>&2
-        echo "$source_lines" 1>&2
-        source_lines_count=1
-    fi
-    context_min="$( echo "$with_file_line_header" | tail -n+2 )"
-    #echo "context_min: $context_min" 1>&2
-    # 3. Filter out non-source lines., and collapse to a single line
-    source="$( echo "$context_min" | egrep -v "$line_regexp" | tr '\n' ' ' )" #"
-    #echo "source: $source" 1>&2
-    # 3a. collapse to a single line
-    source_oneline="$( echo "$source" | tr '\n' ' ' )"
-    #echo "source_oneline: $source_oneline" 1>&2
-    # 4. Get the first ident following the last occurrence of "new" or "sizeof"
-    token="$( echo "$source_oneline" | \
-    egrep '(new|sizeof)([^0-9a-z_]|$)' | \
-    sed -r 's/.*(new|sizeof)([^0-9a-zA-Z_]|$)/\2/' | \
-    sed -r 's/[^0-9a-zA-Z_]*([a-zA-Z0-9_ \*]+).*/\1/' | tr -s '[:blank:]' ' ' )" #"
-    #echo "token: $token" 1>&2
     # 4a. We want the *return address*, not the site of the call per se. Fix this up.
     instr_line_regexp='([0-9a-f]+)[[:blank:]]*<([^-\+]+)([-\+](0x[0-9a-f]+))?>.*'
     next_line="$( tail -c+$(( $bytes_consumed + 1 )) "$tmpfile" 2>/dev/null | sed -rn "/^${instr_line_regexp}/ { s/$instr_line_regexp/\1\t\2\t\4/ ; p; q }" )"
@@ -260,26 +291,57 @@ while read address sym offset; do
     #return_addr_offset="$offset"
     echo "return_addr is $return_addr" 1>&2
     echo "return_addr_sym is $return_addr_sym" 1>&2
-    echo "return_addr_offset is $return_addr_offset" 1>&2
+    echo "return_addr_offset is ${return_addr_offset:=0}" 1>&2
     if [[ "$return_addr_sym" != "$sym" ]]; then
-        echo "Warning: return address for alloc site ${sym}+${offset} does not appear to be in same function, but at ${return_addr_sym}+${return_addr_offset}." 1>&2
+        echo "Warning: return address for alloc site ${sym}${offset} does not appear to be in same function, but at ${return_addr_sym}+${return_addr_offset:-??}." 1>&2
         # we continue
     fi
-    # 5. Print the token and the site
-    #echo "Guessed that site <${sym}+${offset}> allocated: ${token}" 1>&2
-    case "$outputstyle" in
-        (tab)
-            echo "${return_addr_sym}"$'\t'"0x${return_addr}"$'\t'"${filename}"$'\t'"${line_number}"$'\t'$(( $line_number + $source_lines_count ))$'\t'"${token:-\$FAILED\$}"$'\t'"${source_oneline}"
-            ;;
-        (punc)
-            echo "<${return_addr_sym}+${return_addr_offset}> @${filename}:${line_number}"$'\t'"${token:-\$FAILED\$}"
-            ;;
-        (*)
-            echo "<${return_addr_sym}+${return_addr_offset}> @${filename}:${line_number}"$'\t'"${token:-\$FAILED\$}"
-            ;;
-    esac
-done <"$allocsites_tmpfile" | \
-   pad_numbers | sort -t$'\t' -k3 -k4
+    # 5. Compare with addr2line
+    addr2line_filename="$( echo "$addr2line_line" | sed 's/:.*//' )"
+    if [[ "$addr2line_filename" != "??" ]]; then
+        addr2line_filename="$( readlink -f "$addr2line_filename" )"
+    fi
+    addr2line_line_number="$( echo "$addr2line_line" | sed -r 's/.*:([0-9]+)( \(discriminator [0-9]*\))?$/\1/' | sed 's/.*://' )"
+    if [[ "$addr2line_line_number" == "?" ]]; then
+        addr2line_line_number=0
+    fi
+    if [[ "$addr2line_filename" != "${filename:-??}" ]]; then
+        echo "Warning: filenames disagreed: addr2line '$addr2line_filename', objdump '$filename'" 1>&2
+    fi
+    # 6. Print stuff
+    #echo "${return_addr_sym}"$'\t'"0x${return_addr}"$'\t'"${return_addr_offset}"$'\t'"0x${address}"$'\t'"${filename}"$'\t'"${line_number}"$'\t'$(( ${line_number:-0} + ${source_lines_count:-0} ))$'\t'"${token:-\$FAILED\$}"$'\t'"${source_oneline}"
+    echo "${return_addr_sym}"$'\t'"0x${return_addr}"$'\t'"${return_addr_offset}"$'\t'"0x${address}"$'\t'"${addr2line_filename}"$'\t'"${addr2line_line_number}"$'\t'$(( ${addr2line_line_number:-0} + 1 ))$'\t'"${token:-\$FAILED\$}"$'\t'"${source_oneline}"
+done <"$allocsites_tmpfile" 3<"$addr2line_tmpfile" | \
+   pad_numbers | sort -t$'\t' -k5 -k6
+}
 
-# uncomment to help debugging
-rm -f "$tmpfile"
+format_output () {
+    while read return_addr_sym return_addr return_addr_offset address filename line_number line_number_end token source_oneline; do
+        case "$outputstyle" in
+            (tab)
+                if [[ "$return_addr_sym" == "ckd_free" ]]; then
+                    echo "ckd_free: return_addr is: $return_addr" 1>&2
+                    echo "ckd_free: return_addr_offset is: $return_addr_offset" 1>&2
+                    echo "ckd_free: address is: $address" 1>&2
+                    echo "ckd_free: filename is: $filename" 1>&2
+                fi
+                echo "${return_addr_sym}"$'\t'"${return_addr}"$'\t'"${filename}"$'\t'"${line_number}"$'\t'"${line_number_end}"$'\t'"${token}"$'\t'"${source_oneline}"
+                ;;
+            (punc)
+                echo "<${return_addr_sym}+${return_addr_offset}> @${filename}:${line_number}"$'\t'"${token}"
+                ;;
+            (*)
+                echo "<${return_addr_sym}+${return_addr_offset}> @${filename}:${line_number}"$'\t'"${token}"
+                ;;
+        esac
+    done
+}
+
+output_lines="$( generate_output_lines )"
+
+echo "$output_lines" | format_output
+
+# comment to help debugging
+#rm -f "$tmpfile"
+#rm -f "$allocsites_tmpfile"
+#rm -f "$addr2line_tmpfile"
